### ISSUE TITLE
NPM Documentation tweak

### ISSUE THREAD

**Issue by liazy** [ThaNarie/tslint-teamcity-reporter#11]
NPM docs say 'If you have a package.json file in the current directory, you can add an extra "tslint-teamcity" property to it:'

But the property added needs to be: "tslint-teamcity-reporter"

**Comment by ThaNarie** [comment]
@liazy Thanks for noting and reporting, if you create a PR I will merge it immediately :)

**Comment by ThaNarie** [comment]
Thanks!
