### ISSUE TITLE
CLI command does not work

### ISSUE THREAD

**Issue by jcviau** [ThaNarie/tslint-teamcity-reporter#2]
1) The documentation is invalid, the CLI line should be:

tslint --formatters-dir node_modules/tslint-teamcity-reporter/ --format TSHintTeamcity file.ts

2) Also, for this line to work it require to rename teamcity.js to TSHintTeamcityFormatter.js (same name as in the code)

Found this by looking at the tslint documentation:
"Formatter files are always named with the **suffix Formatter** and the exported class within the file must be named Formatter. A formatter is referenced from TSLint without its suffix."

**Comment by mediamonks-arjan** [comment]
Thanks, I will take a look
